### ISSUE TITLE
Qaac error version 4.0

### ISSUE THREAD

**Issue by wingedonezero** [wieslawsoltes/BatchEncoder#190]
Hello i cannot use qaac in version 4.0 no matter what i do it gives me error: progress did not reach 100%. I have tryed both x64 and x86.

**Comment by chros73** [comment]
It works for me. Which format do you want to transcode?
The major change in the template is that the "Input pipe" is off now so maybe that's why it couldn't find the other external utils to use.
In this case you need to have additional libs for flac, etc.

**Comment by wingedonezero** [comment]
From flac qaac is the only one that wont work for me. Every other one works out the box after i download everything.

**Comment by wieslawsoltes** [comment]
Do you have iTunes installed?

**Comment by wieslawsoltes** [comment]
qaac requires Apple Application Support that is included in iTunes or QuickTime. If you are using 64bit Windows, recent 64bit iTunes (ver 12.1 or later) is recommended. 64bit installer for iTunes (iTunes6464Setup.exe) includes both of 32bit and 64bit AppleApplicationSupport, therefore you can run both of qaac.exe and qaac64.exe with it's installation.

**Comment by wieslawsoltes** [comment]
https://sites.google.com/site/qaacpage/

**Comment by wieslawsoltes** [comment]
If not what version do you have installed?

**Comment by wingedonezero** [comment]
I do not have itunes installed maybe that's the problem maybe ill install quicktime i don't want itunes. Ill report back if it helps or not.

**Comment by chros73** [comment]
Actually you don't have to install that bloated sh*t, but you have to download it :)
This topic is a bit complex so I'll try to summarise it, it depends on these settings in your format config!:
- the [Input Extensions](https://github.com/wieslawsoltes/BatchEncoder/wiki/Format-specification#type-input-and-output-extensions) and
- the [Pipe Input](https://github.com/wieslawsoltes/BatchEncoder/wiki/Format-specification#pipes-configuration) checkbox as well
  - that's what changed between v3.1 and v4.0: that's why you experienced your error

**A. using qaac native input formats**
From this [qaac wiki](https://github.com/nu774/qaac/wiki/About-input-format): _"PCM, WAV, ALAC, MP3, 
 AAC(LC), and other LPCM formats supported by Apple AudioFile service. Also, qaac can read cue sheets."_
That means that you don't need anything else to read (transcode) these type of audio files with qaac:
- Input Extensions: `WAV, ALAC, MP3, AAC, MP4`
- Pipe Input: must be unchecked to use it this way

**B. Extending qaac native input formats**
From this [qaac wiki](https://github.com/nu774/qaac/wiki/About-input-format): _"When libsndfile-1.dll is installed with qaac, qaac accepts some more PCM formats available with libsndfile. Similarly, libFLAC.dll installation allows FLAC, wavpackdll.dll for WavPack, and tak_deco_lib.dll for TAK."_
You can download the latest dlls from the first post of this page (thanks to LigH): [lossless_dlls4qaac.7z](https://hydrogenaud.io/index.php/topic,85135.msg947700.html#msg947700) . Then just extract them into the same directory where qaac resides.
You can also download MonkeyAudio in the download section if you want to deal with Ape files this way.
- Input Extensions: `WAV, ALAC, MP3, AAC, MP4, FLAC, WV, APE`
- Pipe Input: still must be unchecked to use it this way (since we still use "native" capability of qaac)

**C. Using other Apple audio framework features**
E.g. like [these](https://github.com/nu774/qaac/wiki/DSP-options-for-convenience).
Now you need the audio framework for these, but if you don't want to use any of these features (and probably a bit more) then you don't need it at all.
Here's how you can "get" it without installing iTunes or QuickTime:
- downloaded iTunes x64, e.g. from [here](https://filehippo.com/download_itunes/64/)
- download and install [7-zip](https://www.7-zip.org/download.html) if you don't have it yet
- download [makeportable.zip](https://sites.google.com/site/qaacpage/cabinet/makeportable.zip?attredirects=0&d=1) from [qaac cabinet](https://sites.google.com/site/qaacpage/cabinet) and extract it into the same directory where iTunes installer is
- run the makeportable batch file
  - it will extract all the required DLL's into subdirectories (QTFiles + QTFiles64) 
- move the resulted QTFiles + QTFiles64 directories to the corresponding qaac flavoured directories that they should exist with qaac.exe or qaac64.exe in the same directory:
  - 32 bit:
    - qaac.exe
    - QTFiles\*.*
  - 64 bit:
    - qaac64.exe
    - QTFiles64\*.*
- download the [icudt55.dll dummy file](https://hydrogenaud.io/index.php/topic,85135.msg907418.html#msg907418) and overwrite the extracted original ones in each QTFiles* directories:
  - from LigH: _"The "makeportable" batch file extracted all the DLL's from the iTunes64 installer which belong to iTunes' whole feature set; qaac needs only the encoder core. For encoding only, most of the content in the icudt55.dll is not required. But the file icudt55.dll can't be deleted, the encoder would refuse to work if it is not present. But you can replace the original files of several MB size with the tiny dummy DLL's, and the encoder still works."_

That's it :) Now you can use e.g. `--normalize` switch with qaac in your format config.

**D. Possible issues with qaac native input and solution for it**
It can happen that certain files (mp3, flac, aac, etc.) can't be encoded this way, probably due to some small errors in these files, but maybe they can by using their external utilities (you have to download those command line utils: flac, lame, etc.).
So, we crate a new format by duplicating our modified qaac-LC format profile, and change these to:
- Title: add e.g. `pipe` to the title
- Input Extensions: `WAV` (we only allow wav input!)
- Pipe Input: must be checked

**E. Summary**
- in this way we have a 2 presets to deal with "natively" supported qaac audio files:
  - use the no-pipe version  always first (it's more efficient)
  - and use the pipe version for those files that failed to be transcoded by the no-pipe format

That's it. :)
@wieslawsoltes, if you like this guide you can put it somewhere on the wiki. And thanks for this really amazing util, again! :)

**Comment by wieslawsoltes** [comment]
@chros73 I have added https://github.com/wieslawsoltes/BatchEncoder/wiki/Tutorial-Using-qaac-without-iTunes. I have enabled wiki editing so you can edit and format if you want.

**Comment by wingedonezero** [comment]
@chros73 Thank you for that that worked perfectly. Nice that i don't have to install all that crap to get it working good. Closing issue since it was resolved and a detailed guide is available now.

**Comment by chros73** [comment]
I'm playing with 1 big flac file + cue sheet. Transcoding into a single file works, but how can I extract tracks into multiple files e.g. into the same dir as the source *.flac and *.cue file is?

**A. transcode 1 big falc+cue file into 1 single m4a file:**
_a. command line:_
`qaac64.exe --tvbr 91 --copy-artwork --normalize --concat *.cue`

_b. BatchEncoder format config:_
- Name: `M4A (MPEG-4/AAC) - qaac - nopipe - cue-single`
- Id: `QAAC_M4A_NOPIPE_CUESINGLE`
- Input ext: `CUE`
- Cmd-line tepmlate: `$EXE $OPTIONS --copy-artwork --ignorelength --concat $INFILE -o $OUTFILE`
- Output path: `$InputPath$\$Name$.$Ext$`

**B. transcode 1 big falc+cue file into multiple m4a files:**
_a. command line:_
`qaac64.exe --tvbr 91 --copy-artwork --normalize --fname-format "${tracknumber}${artist& }${artist} -${title& }${title}" *.cue`

_b. BatchEncoder format config:_
- Name: `M4A (MPEG-4/AAC) - qaac - nopipe - cue-multi`
- Id: `QAAC_M4A_NOPIPE_CUESMULTI`
- Input ext: `CUE`
- Cmd-line tepmlate: `$EXE $OPTIONS --copy-artwork --ignorelength --fname-format "${tracknumber}${artist& }${artist} -${title& }${title}" $INFILE`
- Output path: `$InputPath$\$Name$.$Ext$`

Note that `-o $OUTFILE` is missing from Cmd-line tepmlate!
It's kind of working: it always spits out the files into the base directory where BatchEncoder is, no matter what the Output path is!

I know it's a tricky case, what do you think?

**Comment by wieslawsoltes** [comment]
@chros73 Try adding to cmd-line tepmlate:  `-d $OUTPATH`.

**Comment by chros73** [comment]
I tried it with command line by adding `-d .` to the end and it works, but not in BatchEncoder, Cmd-line tepmlate: 
`$EXE $OPTIONS --copy-artwork --ignorelength --fname-format "${tracknumber}${artist& }${artist} -${title& }${title}" $INFILE -d $OUTPATH`

The result: "Error: progress didn't reach 100%"

**Comment by wieslawsoltes** [comment]
Probably issue with progress script, the output of qaac to console must be different. 

https://github.com/wieslawsoltes/BatchEncoder/blob/master/config/progress/GetProgress_QaacEnc.lua

It expects something like this:
```lua
-- GetProgress_QaacEnc

function GetProgress(s) 
  if string.match(s, '%ssamples processed%s') ~= nil then return "100";
  else return string.match(s, '%[(%d+.%d+)%%%]'); end;
end

p = GetProgress("[18.4%] 11:12.333/1:00:46.041 (79.8x), ETA 0:37.250 ")
print(p)
assert(p == "18.4")

p = GetProgress("11406949/11406949 samples processed in 0:03.281")
print(p)
assert(p == "100")
```

**Comment by wieslawsoltes** [comment]
Can you capture qaac console output and post here.

**Comment by chros73** [comment]
How can I capture it?

**Comment by wieslawsoltes** [comment]
Try using command-line and pipe output to a file, add at the end of command line `> output.txt`.

**Comment by chros73** [comment]
Errr... I don't understand: are you talking about running "BatchEncoder.exe" via command-line? If so, how?
I quickly went through the wiki for examples but I haven't found any.
Or are you talking about to run and log "qaac.exe" itself?

**Comment by wieslawsoltes** [comment]
`qaac64.exe --tvbr 91 --copy-artwork --normalize --fname-format "${tracknumber}${artist& }${artist} -${title& }${title}" *.cue > output.txt`

But run with single cue file as it would using BatchEncoder.

**Comment by chros73** [comment]
output.txt is empty. I think I need `tee.exe` to redirect the normal output to a file. :)
But it looks like this in the console:
```
01 foo1 - bar1.m4a
Scanning maximum peak...
[100.0%] 3:40.666/3:40.666 (391.9x), ETA 0:00.000
9731400/9731400 samples processed in 0:00.563
Peak value: 0.977234
AAC-LC Encoder, TVBR q91, Quality 96
[100.0%] 3:40.666/3:40.666 (36.6x), ETA 0:00.000
9731400/9731400 samples processed in 0:06.030
Overall bitrate: 207.187kbps
Optimizing...done

02 foo2 - bar2.m4a
Scanning maximum peak...
[100.0%] 4:33.413/4:33.413 (460.3x), ETA 0:00.000
12057528/12057528 samples processed in 0:00.594
Peak value: 1
AAC-LC Encoder, TVBR q91, Quality 96
[100.0%] 4:33.413/4:33.413 (36.8x), ETA 0:00.000
12057528/12057528 samples processed in 0:07.421
Overall bitrate: 196.863kbps
Optimizing...done
```

**Comment by wieslawsoltes** [comment]
I will have to reproduce on my machine. Will take a look as soon I will have time.

**Comment by chros73** [comment]
No worries, thanks.
I don't think it's a problem with the progress indicator, otherwise it shouldn't work without the `-d $OUTPATH`.
I think it's rather the `$OUTPATH` variable. Where's this value should come from? Is it the "Output path" value at the bottom of the main window?

**Comment by wieslawsoltes** [comment]
The output path without file name.

**Comment by chros73** [comment]
OK, so it should come from the "Output path" value at the bottom of the main window.
I tried 3 values with it, all of them result the same error:
- empty
- `$InputPath$`
- `$InputPath$\$Name$.$Ext$`

Yep, I just tried out with 1 small file (flac), and I also got the same error:
`$EXE $OPTIONS --copy-artwork --ignorelength $INFILE -d $OUTPATH`

While the cmd-line version works:
`qaac64.exe --tvbr 91 --copy-artwork --ignorelength --normalize foo.flac -d "d:\foobar\music - acc\try - 2"`

So it's definitely the `$OUTPATH` variable.

**Comment by wieslawsoltes** [comment]
Try using full path instead of $OUTPATH in format configuration.

**Comment by chros73** [comment]
Hhmm, it doesn't work either (not even with 1 small file) :)
`$EXE $OPTIONS --copy-artwork --ignorelength $INFILE -d "d:\foobar\music - acc\try - 2"`

**Comment by wieslawsoltes** [comment]
Ok. Will have to debug this.
