### ISSUE TITLE
[Bug Report] Conversion fails with m4a source files

### ISSUE THREAD

**Issue by ghost** [wieslawsoltes/BatchEncoder#195]
Hello. I'm using BatchEncoder v4.0 but I'm encountering an issue when converting m4a files to any other format.
Error: can not create command-line process(0)

I don't have this kind of problem when the source files are WAV or mp3.
I think the problem is that BatchEncoder does not automatically decode the m4a file to WAV and then convert the wav file to the chosen format-encoder (while passing metadata, cover art as well).
Please fix this problem.

**Comment by wieslawsoltes** [comment]
You are probably missing decoder executable.

**Comment by nickbe** [comment]
Same problem here. qaac is definetely installed since encoding works. But as soon a I start to use m4a as a source it's not working.
So the qeustion here is:

How should I define the settings when I want to transcode from m4a to m4a - OR even better how can I tell BachEncoder to simply copy m4a files from source to destination?
